name: miejscowki_map
description: Interfejs mapy miejscówek inspirowany dostarczonym zrzutem ekranu.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.13.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.2
  flutter_svg: ^2.0.17
  geolocator: ^14.1.1
  http: ^1.6.0
  latlong2: ^0.10.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.3
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/focus_map_logo.svg
    - assets/logo_github.svg
